# G-CLEF Wavefinder Configuration File
# This file is written in TOML: https://toml.io/en/
# See Explanation of Options at the bottom of the file.

[app]
update_rate = 0.016667

[camera]
run_mode    = "NORMAL"
bits        = 12
freq_mode   = 0
resolution  = {rows = 1280, columns = 960}
bin_mode    = "NO_BIN"
nBuffer     = 24
exposure    = 5.0
fps         = 5.0
gain        = 15

[image]
full_threshold  = 15.0
roi_threshold   = 15.0
roi_size        = {x = 50, y = 50}
use_roi_stats   = false
fwhm_method     = "variance"

[monochromator]
port = "COM9"

[motion.zaber]
ports = [
    "COM1",
    "COM2",
    "COM3",
    "COM4",
    "COM5",
    "COM6",
    "COM7",
    "COM8",
    "COM9",
    "COM10"
]

[motion.zaber.axis_names]
"detector x"    = {sn = 122711,  keyword = "detxpos"}
"detector y"    = {sn = 122712,  keyword = "detypos"}
"detector z"    = {sn = 33939,  keyword = "detzpos"}
"cfm2 x"        = {sn = 110098, keyword = "cfm2xpos"}
"cfm2 y"        = {sn = 113059, keyword = "cfm2ypos"}

[motion.galil]
address         = "192.168.1.1900000000000"
acceleration    = 2000000
deceleration    = 2000000
move_speed      =  100000
home_speed      =    5000
encdr_cnts_deg  =     800
drive_cnts_deg  =   10000

[motion.galil.axis_names]
"cfm1 azimuth"      = {ch = "A", keyword = "cfm1az"}
"cfm1 elevation"    = {ch = "B", keyword = "cfm1el"}
"cfm2 azimuth"      = {ch = "C", keyword = "cfm2az"}
"cfm2 elevation"    = {ch = "D", keyword = "cfm2el"}

[motion.limits]
"detector z"        = {min =   0.0, max = 17.5}
"cfm1 azimuth"      = {min = -30.0, max = 30.0}
"cfm1 elevation"    = {min = -30.0, max = 30.0}
"cfm2 azimuth"      = {min = -30.0, max = 30.0}
"cfm2 elevation"    = {min = -30.0, max = 30.0}

[sequencer]
x_axis      = "detector x"
y_axis      = "detector y"
z_axis      = "detector z"

[sequencer.focus]
points_per_pass     = 10
frames_per_point    =  3
minimum_move        =  0.001

# Explanation of Options
# Any settings not set will use defaults, shown in [brackets]
# 
# [app]
# update rate in seconds; default = 1/60
#
# [image]
# full_threshold:   full-frame threshold for image processing, as a percentage
#                       70.0 means all pixels less than 70% of saturation are
#                       set to zero for image processing (centroid, FWHM), default [50.0]
# roi_threshold:    same as full_threshold, but for the region of interest
#                       sub-image, default [50.0]
# roi_size:         size of ROI bounding box in pixels, default [{x = 50, y = 50}]
# use_roi_stats:    true to use the region of interest for all image processing,
#                       false to use the full frame
# fwhm_method:      full-width half-maximum calculation method is one of
#                       ["variance"], "encircled_pixels", "encircled_energy",
#                       "weighted_encircled_energy"
#
# [camera]
# run_mode:     ["NORMAL"] (streaming video) or "TRIGGER" (single exposure)
# bits:         camera bitrate [8] or 12
# freq_mode:    freq = full_speed / (2^freq_mode), is one of [0], 1, 2, 3, 4
# resolution:   camera resolution: [1280, 960]
# bin_mode:     camera bin mode is one of
#                   ["NO_BIN"], "BIN1X2", "BIN1X3", "BIN1X4", "SKIP"
# nBuffer:      size of camera buffer, maximum of [24]
# exposure:     exposure time in milliseconds, in increments of 0.05ms,
#                   default [50.0]
# fps:          "NORMAL" mode target frames per second, default [10.0]
# gain:         6 to 41 dB, inclusive, [15] dB recommended for "NO_BIN" mode,
#                   lower to 6-8 for binning modes
#
# [monochromator]
# port:         port to look for monochromator, COM or tty
#
# [motion.zaber]
# ports:        list of serial ports to scan [all]
#
# [motion.zaber.axis_names]
# list all zaber axes as "name" = {sn = serial_number, keyword = "kw"}, e.g.
# "detector x" = {sn = 33938,  keyword = "detxpos"}
# keyword is for FITS header, limited to 8 chars
#
# [motion.galil]
# address:      IP address of Newmark controller ["192.168.1.19"]
# acceleration: in drive counts [2000000]
# deceleration: in drive counts [2000000]
# move_speed:   in drive counts [100000]
# home_speed:   in drive counts [5000]
# encdr_cnts_deg:   encoder counts per degree [800]
# drive_cnts_deg:   drive counts per degree [10000]
#
# [motion.galil.axis_names]
# list all galil/newmark axes as "name" = {ch = "channel letter", keyword = "kw"}, e.g.
# "cfm1 azimuth" = {ch = "A", keyword = "cfm1az"}
# keyword is for FITS header, limited to 8 chars
#
# [motion.limits]
# list all motion limits (both zaber & galil) as "name" = {min = XX, max = XX}
# where min and max are the minimum and maximum position in mm or degrees, e.g.
# "focal_z" = {min =   0.0, max = 15.0}
# "cfm1_az" = {min = -10.0, max = 10.0}
#
# [sequencer]
# x_axis: name of axis to use as x-axis when positioning camera
# y_axis: name of axis to use as y-axis when positioning camera
# z_axis: name of axis to use as z-axis when focusing camera
#
# [sequencer.focus]
# points_per_pass:  number of focus points per focusing pass [10]
# frames_per_point: number of frames to measure at each point (averaged) [3]
# minimum_move:     minimum focus movement resolution, in mm [0.001]
